const ClassroomLocations = [
  {
    id: 1,
    name: "Class 1",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
    status: "available",
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Standard classroom with projector and whiteboard",
    floor: "1st Floor • Robert A. Pastor E-Learning Center",
    seats: 30,
    amenities: ["Projector", "Whiteboard", "Air Conditioning", "WiFi"],
    icon: "school",
    iconColor: "#2563eb",
  },
  {
    id: 2,
    name: "Class 2",
    status: "occupied",
    statusColor: "#dc2626",
    statusBg: "#fecaca",
    description: "Small classroom ideal for seminars",
    floor: "1st Floor • Robert A. Pastor E-Learning Center",
    seats: 25,
    amenities: ["Smart Board", "Air Conditioning", "WiFi"],
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 3,
    name: "Class 3",
    status: "available",
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Large lecture hall with tiered seating",
    floor: "1st Floor • Robert A. Pastor E-Learning Center",
    seats: 80,
    amenities: ["Projector", "Microphone System", "Tiered Seating", "WiFi"],
    icon: "presentation",
    iconColor: "#7c3aed",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 4,
    name: "Class 7",
    status: "maintenance",
    statusColor: "#ca8a04",
    statusBg: "#fef9c3",
    description: "Computer lab with latest software",
    floor: "2nd Floor • Robert A. Pastor E-Learning Center",
    seats: 40,
    amenities: ["40 Computers", "Software Suite", "Printer", "WiFi"],
    icon: "computer",
    iconColor: "#16a34a",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 5,
    name: "Class 8",
    status: "available",
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Meeting room for faculty and staff",
    floor: "3rd Floor • Robert A. Pastor E-Learning Center",
    seats: 15,
    amenities: ["Conference Table", "Video Conferencing", "Whiteboard", "WiFi"],
    icon: "group",
    iconColor: "#ea580c",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 6,
    name: "ADS 101",
    status: "occupied",
    statusColor: "#dc2626",
    statusBg: "#fecaca",
    description: "Main lecture hall for large classes",
    floor: "1st Floor • Arts and Sciences",
    seats: 120,
    amenities: [
      "Stage",
      "Microphone System",
      "Projector",
      "Recording Equipment",
    ],
    icon: "presentation",
    iconColor: "#7c3aed",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
];

const AdministrationLocations = [
  {
    id: 1,
    name: "President Office",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Private office for the university president",
    floor: "1st Floor • Robert A. Pastor E-Learning Center",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 2,
    name: "Provost Office",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Private office for the university provost",
    floor: "3rd Floor • Arts and Sciences",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 3,
    name: "Student Affairs",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Office for student affairs and support services",
    floor: "Admin 1",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
];

const DormitoriesLocations = [
  {
    id: 1,
    name: "Dorm AA",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Female dormitory with shared rooms and common areas",
    // floor: "Admin 1",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 2,
    name: "Gabriel Volpy Boys",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Male dormitory with single and double rooms",
    // floor: "Admin 1",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 3,
    name: "Aisha Kande",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Female dormitory with suite-style living",
    // floor: "Admin 1",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
];

const DiningRecreationLocations = [
  {
    id: 1,
    name: "Main Cafeteria",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Main dining area with diverse food options",
    //   floor: "Admin 1",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 2,
    name: "Coffee Shop",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Casual coffee shop with snacks and beverages",
    floor: "1st Floor • Arts and Sciences",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 3,
    name: "Gym Center",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Gym and fitness center with various equipment",
    floor: "Commencement Hall",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
];

const AcademicAdvisingLocations = [
  {
    id: 1,
    name: "Academic Advisor",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Student academic advising office",
    floor: "2nd Floor • Robert A. Pastor E-Learning Center",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 2,
    name: "Registrar Office",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Office for student records and registration",
    floor: "2nd Floor • Arts and Sciences",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 3,
    name: "Library",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Campus library with study areas and resources",
    floor: "3rd Floor • Robert A. Pastor E-Learning Center",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
];

const HealthServicesLocations = [
  {
    id: 1,
    name: "Health Center",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description:
      "Health center providing medical services to students and staff",
    // floor: "Admin 1",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 2,
    name: "Copy Center",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Copy center providing copying and printing services",
    floor: "Commencement Hall",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
  {
    id: 3,
    name: "Campus Store",
    directions: [{}],
    statusColor: "#16a34a",
    statusBg: "#dcfce7",
    description: "Campus store offering textbooks, supplies, and merchandise",
    floor: "Commencement Hall",
    icon: "school",
    iconColor: "#2563eb",
    directions: [
      {
        id: "1",
        instruction: "Head past the bus stop after exiting the cafeteria",
        distance: "200m",
        time: "3 mins",
        type: "start",
      },
      {
        id: "2",
        instruction:
          "Turn right at the intersection and head straight to Robert A. Pastor Library and E-learning Center",
        distance: "100m",
        time: "2 mins",
        type: "turn",
      },
      {
        id: "3",
        instruction: "Your destination, Main Library",
        distance: "0m",
        time: "0 mins",
        type: "destination",
      },
    ],
  },
];

export const BuildingCategories = {
  Classrooms: ClassroomLocations,
  Administration: AdministrationLocations,
  Dormitories: DormitoriesLocations,
  "Dining & Recreation": DiningRecreationLocations,
  "Academic Support": AcademicAdvisingLocations,
  "Health & Services": HealthServicesLocations,
};
